version: '3.5'

services:
  postgres:
    image: honeur/postgres:9.6-omopcdm-5.3.1
    container_name: postgres
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - shared:/var/lib/postgresql/envfileshared
    restart: always
    environment:
      - "POSTGRES_PASSWORD=h0n3uR#2019!"
    networks:
      - honeur-net
    command:
      - /bin/sh
      - -c
      - |
          mkdir -p /var/lib/postgresql/envfileshared
          cp /var/lib/postgresql/envfile/honeur.env /var/lib/postgresql/envfileshared/honeur.env
          docker-entrypoint.sh postgres
  webapi:
    image: honeur/webapi-atlas:2.6.0-1.1.5
    container_name: webapi
    ports:
      - "8080:8080"
    volumes:
      - shared:/var/lib/shared
    restart: always
    depends_on:
      - "postgres"
    environment:
      - "BACKEND_HOST=http://localhost:8080"
      - "LDAP_URL=ldap://ldap.forumsys.com:389"                     # default value, not used in standard setup but required for webapi
      - "LDAP_SYSTEM_USERNAME=cn=read-only-admin,dc=example,dc=com" # default value, not used in standard setup but required for webapi
      - "LDAP_SYSTEM_PASSWORD=password"                             # default value, not used in standard setup but required for webapi
      - "LDAP_BASE_DN=dc=example,dc=com"                            # default value, not used in standard setup but required for webapi
      - "LDAP_DN=uid={0},dc=example,dc=com"                         # default value, not used in standard setup but required for webapi
    networks:
      - honeur-net
    command:
      - /bin/sh
      - -c
      - |
          sed -i -e 's@http://localhost:8080@'"$${BACKEND_HOST}"'@g' /usr/local/tomcat/webapps/atlas/js/config-local.js
          cp /var/lib/shared/honeur.env /usr/local/tomcat/bin/setenv.sh
          catalina.sh run
  zeppelin:
    image: honeur/zeppelin:0.8.0
    container_name: zeppelin
    ports:
      - "7077:7077"
      - "8082:8080"
    volumes:
      - ./zeppelin/logs:/logs
      - ./zeppelin/notebook:/notebook
    restart: always
    depends_on:
      - "postgres"
    environment:
      - "ZEPPELIN_NOTEBOOK_DIR=/notebook"
      - "ZEPPELIN_LOG_DIR=/logs"
    networks:
      - honeur-net

networks:
  honeur-net:
    name: honeur-net

volumes:
  pgdata:
    external: true
  shared:
    external: true
