version: '3.5'

services:
  postgres:
    image: honeur/postgres:PHEDERATION-9.6-omopcdm-5.3.1-webapi-2.7.1-1.4
    container_name: postgres
    security_opt:
      - no-new-privileges
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - shared:/var/lib/postgresql/envfileshared
    restart: always
    networks:
      - honeur-net
    command:
      - /bin/sh
      - -c
      - |
          mkdir -p /var/lib/postgresql/envfileshared
          cp /var/lib/postgresql/envfile/honeur.env /var/lib/postgresql/envfileshared/honeur.env
          python3 /var/lib/postgresql/setup-scripts/update_password_with_envfile.py &
          docker-entrypoint.sh postgres

  webapi:
    image: honeur/webapi-atlas:2.7.1-1.4-standard
    container_name: webapi
    security_opt:
      - no-new-privileges
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: shared
        target: /var/lib/shared
        read_only: true
    restart: always
    depends_on:
      - "postgres"
    environment:
      - "BACKEND_HOST=http://localhost:8080"
      - "OHDSI_DATASOURCE_URL=jdbc:postgresql://postgres:5432/OHDSI"
    networks:
      - honeur-net
    command:
      - /bin/sh
      - -c
      - |
          sed -i -e 's@http://localhost:8080@'"$${BACKEND_HOST}"'@g' /usr/local/tomcat/webapps/atlas/js/config-local.js
          cp /var/lib/shared/honeur.env /usr/local/tomcat/bin/setenv.sh
          catalina.sh run

  zeppelin:
    image: honeur/zeppelin:0.8.0-1.4
    container_name: zeppelin
    security_opt:
      - no-new-privileges
    ports:
      - "7077:7077"
      - "8082:8080"
    volumes:
      - ./zeppelin/logs:/logs
      - ./zeppelin/notebook:/notebook
    restart: always
    depends_on:
      - "postgres"
    environment:
      - "ZEPPELIN_NOTEBOOK_DIR=/notebook"
      - "ZEPPELIN_LOG_DIR=/logs"
    networks:
      - honeur-net

networks:
  honeur-net:
    name: honeur-net

volumes:
  pgdata:
    external: true
  shared:
    external: true
