version: '3'

services:
  postgres:
    image: honeur/postgres
    container_name: postgres
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - shared:/var/lib/postgresql/envfileshared
    restart: always
    environment:
      POSTGRES_PASSWORD=h0n3uR#2019!
    command:
      - /bin/sh
      - -c
      - |
          mkdir -p /var/lib/postgresql/envfileshared
          cp /var/lib/postgresql/envfile/honeur.env /var/lib/postgresql/envfileshared/honeur.env
          docker-entrypoint.sh postgres

  webapi:
    image: honeur/webapi-atlas
    container_name: webapi
    ports:
      - "8080:8080"
    volumes:
      - shared:/var/lib/shared
    restart: always
    depends_on:
      - "postgres"
    environment:
      BACKEND_HOST=http://localhost:8080
      LDAP_URL=ldap://ldap.forumsys.com:389
      LDAP_SYSTEM_USERNAME=cn=read-only-admin,dc=example,dc=com
      LDAP_SYSTEM_PASSWORD=password
      LDAP_BASE_DN=dc=example,dc=com
      LDAP_DN=uid={0},dc=example,dc=com
    command:
      - /bin/sh
      - -c
      - |
          sed -i -e 's@http://localhost:8080@'"$${BACKEND_HOST}"'@g' /usr/local/tomcat/webapps/atlas/js/config-local.js
          cp /var/lib/shared/honeur.env /usr/local/tomcat/bin/setenv.sh
          catalina.sh run

  user-mgmt:
    image: honeur/user-mgmt
    container_name: user-mgmt
    ports:
      - "8081:8080"
    volumes:
      - shared:/var/lib/shared
    restart: always
    depends_on:
      - "postgres"
    environment:
      BACKEND_HOST=http://localhost:8081
      USERMGMT_ADMIN_USERNAME=admin
      USERMGMT_ADMIN_PASSWORD=admin
    command:
      - /bin/sh
      - -c
      - |
          sed -i -e 's@http://localhost:8081@'"$${BACKEND_HOST}"'@g' /usr/local/tomcat/webapps/usermgmt/main.js
          cp /var/lib/shared/honeur.env /usr/local/tomcat/bin/setenv.sh
          catalina.sh run

  zeppelin:
    image: honeur/zeppelin
    container_name: zeppelin
    ports:
      - "7077:7077"
      - "8082:8080"
    volumes:
      - shared:/var/lib/shared
      - ./zeppelin/logs:/logs
      - ./zeppelin/notebook:/notebook
    restart: always
    depends_on:
      - "postgres"
    command:
      - /bin/bash
      - -c
      - |
        cp /var/lib/shared/honeur.env /zeppelin/bin/zeppelin-env.sh
        sed -i -e 's/^/export /' /zeppelin/bin/zeppelin-env.sh
        source /zeppelin/bin/zeppelin-env.sh
        alias python=python3
        alias pip=pip3
        bin/zeppelin.sh
    environment:
      ZEPPELIN_SECURITY=jdbc
      LDAP_URL=ldap://ldap.forumsys.com:389
      LDAP_BASE_DN=dc=example,dc=com
      LDAP_DN=uid={0},dc=example,dc=com
      ZEPPELIN_NOTEBOOK_DIR=/notebook
      ZEPPELIN_LOG_DIR=/logs

networks:
  default:

volumes:
  pgdata:
    external: true
  shared:
    external: true
