version: '3.5'
services:
  omop-indexes-and-constraints:
    image: honeur/postgres:omop-cdm-constraints-and-indexes-latest
    container_name: omop-indexes-and-constraints
    volumes:
      - shared:/var/lib/shared
    external_links:
      - postgres
    networks:
      - honeur-net
    environment:
      - "DB_HOST=postgres"

networks:
  honeur-net:
    external: true

volumes:
  shared:
    external: true