version: '3'
services:
  omop-indexes-and-constraints:
    container_name: omop-indexes-and-constraints
    volumes:
      - ./setup-conf:/postgres/setup-scripts/conf
      - shared:/var/lib/shared
    image: honeur/postgres-omop-cdm-constraints-and-indexes
    external_links:
      - postgres
    networks:
      - honeur-net
    command:
      - /bin/bash
      - -c
      - |
          source /postgres/setup-scripts/setenv.sh
          python -u indexes_and_constraints_omopcdm.py conf/setup.yml

networks:
  honeur-net:
    name: honeur-net
  
volumes:
  shared:
    external: true